# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'int.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(788, 560)
        Main.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(Main)
        self.centralwidget.setObjectName("centralwidget")
        self.Login = QtWidgets.QFrame(self.centralwidget)
        self.Login.setGeometry(QtCore.QRect(10, 140, 781, 391))
        self.Login.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Login.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Login.setObjectName("Login")
        self.pushButton = QtWidgets.QPushButton(self.Login)
        self.pushButton.setGeometry(QtCore.QRect(400, 240, 91, 31))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.Login)
        self.label_3.setGeometry(QtCore.QRect(280, 128, 47, 13))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.Login)
        self.lineEdit_2.setGeometry(QtCore.QRect(370, 78, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.Login)
        self.lineEdit_3.setGeometry(QtCore.QRect(370, 118, 113, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit = QtWidgets.QLineEdit(self.Login)
        self.lineEdit.setGeometry(QtCore.QRect(370, 38, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.Login)
        self.lineEdit_4.setGeometry(QtCore.QRect(370, 158, 113, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_4 = QtWidgets.QLabel(self.Login)
        self.label_4.setGeometry(QtCore.QRect(280, 168, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.Login)
        self.label_2.setGeometry(QtCore.QRect(280, 88, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.Login)
        self.label.setGeometry(QtCore.QRect(280, 38, 47, 13))
        self.label.setObjectName("label")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.Login)
        self.commandLinkButton.setGeometry(QtCore.QRect(330, 300, 185, 41))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 111, 111))
        self.label_7.setStyleSheet("background-image: url(:/newPrefix/Capture2.PNG);")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/newPrefix/Capture2.PNG"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(340, 110, 161, 20))
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(160, 10, 531, 51))
        self.label_5.setObjectName("label_5")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(220, 80, 401, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_7.raise_()
        self.label_6.raise_()
        self.label_5.raise_()
        self.line.raise_()
        self.Login.raise_()
        Main.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Main)
        self.statusbar.setObjectName("statusbar")
        Main.setStatusBar(self.statusbar)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "MainWindow"))
        self.pushButton.setText(_translate("Main", "Valider"))
        self.label_3.setText(_translate("Main", "ID"))
        self.label_4.setText(_translate("Main", "Code PIN"))
        self.label_2.setText(_translate("Main", "Prénom"))
        self.label.setText(_translate("Main", "Nom"))
        self.commandLinkButton.setText(_translate("Main", "CommandLinkButton"))
        self.label_6.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#00557f;\">Elections Legislatives</span></p></body></html>"))
        self.label_5.setText(_translate("Main", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; font-style:italic; color:#00557f;\">République Algérienne Démocratique et Populaire </span></p><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; font-style:italic; color:#00557f;\">Autorité Nationale Indépendante des Elections</span></p></body></html>"))
import test_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main = QtWidgets.QMainWindow()
    ui = Ui_Main()
    ui.setupUi(Main)
    Main.show()
    sys.exit(app.exec_())
